version: '3.3'

services:

  nerd-dinner-db:
    ports:    
      - "1433"

  kibana:
    ports:    
      - "5601"

  nerd-dinner-web:
    ports:
      - "80"

networks:
  nd-net:
    external:
      name: nat