version: '3.3'

services:

  signup-app:
    build:
      context: ../
      dockerfile: ./docker/web/Dockerfile

  signup-save-handler:
    build:
      context: ../
      dockerfile: ./docker/save-handler/Dockerfile

  signup-index-handler:
    build:
      context: ../
      dockerfile: ./docker/index-handler/Dockerfile