version: '3.3'

services:

  signup-db:
    ports:    
      - 1433

  kibana:
    ports:
      - 5601

  signup-app:
    ports:
      - 80

  message-queue:
    ports:
      - 4222

  elasticsearch:
    ports:
      - 9200

  signup-save-handler:
    ports:
      - 135

networks:
  app-net:
    external:
      name: nat