version: '3.3'

services:

  signup-db:
    deploy:
      endpoint_mode: dnsrr

  message-queue:
    deploy:
      endpoint_mode: dnsrr

  elasticsearch:
    deploy:
      endpoint_mode: dnsrr

  signup-app:
    image: dockeronwindows/ch10-newsletter-web:${VERSION_NUMBER}
    ports:
      - mode: host
        target: 80
        published: 80
    deploy:
      endpoint_mode: dnsrr

  signup-save-handler:
    image: dockeronwindows/ch10-newsletter-save-handler:${VERSION_NUMBER}
    deploy:
      endpoint_mode: dnsrr

  signup-index-handler:
    image: dockeronwindows/ch10-newsletter-index-handler:${VERSION_NUMBER}
    deploy:
      endpoint_mode: dnsrr

  kibana:
    ports:
      - mode: host
        target: 5601
        published: 5601
    deploy:
      endpoint_mode: dnsrr

networks:
  app-net: