version: '3.3'

services:
  
  message-queue:
    image: nats:nanoserver
    networks:
      - nd-net

  elasticsearch:
    image: sixeyed/elasticsearch:nanoserver
    volumes:
      - es-data:C:\data
    networks:
      - nd-net

  nerd-dinner-db:
    image: dockeronwindows/ch07-nerd-dinner-db
    volumes:
      - db-data:C:\data
    networks:
      - nd-net

  kibana:
    image: sixeyed/kibana:nanoserver
    networks:
      - nd-net

  nerd-dinner-save-handler:
    image: dockeronwindows/ch07-nerd-dinner-save-handler
    networks:
      - nd-net

  nerd-dinner-index-handler:
    image: dockeronwindows/ch05-nerd-dinner-index-handler
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
    networks:
      - nd-net

  nerd-dinner-homepage:
    image: dockeronwindows/ch03-nerd-dinner-homepage
    networks:
      - nd-net

  nerd-dinner-web:
    image: dockeronwindows/ch07-nerd-dinner-web
    environment: 
      - HOMEPAGE_URL=http://nerd-dinner-homepage
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
    networks:
      - nd-net

networks:
  nd-net:

volumes:
  es-data:
  db-data: